### ISSUE TITLE
Different Values for the Example...

### ISSUE THREAD

**Issue by danzen** [colinmeinke/svg-arc-to-cubic-bezier#7]
Hi there... I have been trying out the function and when using your example, I get different values for the answer.  Also... I can't seem to make it work in general - sometimes it does but not often.  Could you please confirm?

Here is the console results I got from running your code with the sample provided:
Object { x1: 100, y1: -10.383004898799982, x2: 565.5745073482001, y2: 300, x: 400, y: 300 }
Object { x1: 234.42549265180003, y1: 300, x2: 700, y2: -10.383004898799996, x: 700, y: 100 }

When I try the equations with the SVG from https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths for arcs - the SVG is provided near the end of the page... it gives me cubic Beziers that as far as I can tell... are not working.  The first one works - but the various flag ones do not match up.  I am doing some complex work to convert to my system - but I have triple checked it and the fact that the sample code does not yield the same results that you have posted has led to this issue post ;-).

![arcs](https://user-images.githubusercontent.com/380281/51448039-a4421100-1cf1-11e9-9677-196d5f4bcdce.jpg)

Look forward to your reply - and thanks for the work in putting this together - hope we can solve it!

**Comment by danzen** [comment]
For easy reference, here is the answer posted for your example...
// [
//   {
//     x1: 159.7865795437111,
//     y1: 244.97474575043722,
//     x2: 342.5677510865157,
//     y2: 362.49999701503634,
//     x: 508.253174689854,
//     y: 362.4999967447917,
//   },
//   {
//     x1: 673.9385982931924,
//     y1: 362.49999647454695,
//     x2: 759.7865756485664,
//     y2: 244.97474477179443,
//     x: 699.9999995964145,
//     y: 99.99999902135724,
//   },
// ]

**Comment by colinmeinke** [comment]
@danzen thanks for reporting this. There is definitely a problem here. I have an example of the issue here https://codepen.io/colinmeinke/pen/wNGjEZ. It appears there was a bug introduced in this pull request https://github.com/colinmeinke/svg-arc-to-cubic-bezier/pull/4, if you switch the codepen dependency back to version 3.0.0 it works as expected - @jwir3
would you like to have a go at fixing this, or shall I simply revert the commit? For now the solution is to use 3.0.0 which is the version before the issue was introduced.

**Comment by jwir3** [comment]
It's probably good we determine what is happening - if it's an edge case or something. I think it's a good idea to back out in the interim, but I can say we're using this in production on Invision studio and not seeing errors with ellipses in general, so I wonder if there is some thing numerical happening at those specific points.

**Comment by jwir3** [comment]
@CodeDacu have you seen anything like this in the application?

**Comment by colinmeinke** [comment]
@jwir3 the commonality between the two shapes that are incorrect is that they both have `sweep-flag` set to `0`, rather than `1`. From the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#Arcs):

> The second argument is the sweep-flag. It determines if the arc should begin moving at positive angles or negative ones, which essentially picks which of the two circles you will travel around.

I guess by changing to a constant rather than making a calculation based on a variable, the code now assumes direction of travel.

**Comment by jwir3** [comment]
Hmmm... it looks like the only one that's correct in the above rendering is when the sweep-flag is 0 AND the large-arc-sweep-flag is 0. It doesn't look like any of the others are correct, unless I'm mistaken?

**Comment by colinmeinke** [comment]
@jwir3 I don't think the image by the OP is correct, those paths seem way off, no idea what's happening there. There is definitely an issue though, as shown by the demo I created here https://codepen.io/colinmeinke/pen/wNGjEZ - paths 3 and 4 appear to be traced correctly, however paths 1 and 2 are not.

**Comment by colinmeinke** [comment]
@jwir3 that's strange, are you getting any errors in the console? In both Chrome and Firefox I see the following:

![](https://www.dropbox.com/s/enizleiijmnpwws/Screenshot%202019-01-28%20at%2017.42.23.png?raw=true)

There should be a 50% opacity black copy of each shape overlaid with beziers instead of arcs.

**Comment by jwir3** [comment]
Odd... Now I do see it. Did something change in the codepen? I suspect not, since then I think the hash would change...

**Comment by jwir3** [comment]
Bisecting reveals that this is the commit that caused the problems:
```
commit cffe7461249e7bcdd104a7a34730eec583dc9db9
Author: Scott Johnson <jaywir3@gmail.com>
Date:   Tue Mar 13 09:24:56 2018 -0500

    Adjust the constant to use the more accurate spencermortensen version.

:040000 040000 27b5f9f4ccd84148c0af77c2ae4791050b2e8bf3 30d3aa890a60933175c865d72f05985374303af7 M	src
```

I'm digging in further right now to see what was actually the problem in this commit.

**Comment by jwir3** [comment]
I found the issue. The original code was dependent on the sign of `ang2`, which means that it could be either positive or negative. If ang2 was negative, the constant would also be negative. However, the new code is always positive, and since `ang2` is positive if `sweep-flag` is 1 and negative if `sweep-flag` is 0, half of the cases didn't work.

I'm making a patch right now.

**Comment by danzen** [comment]
Excellent thanks!  Will try it out.
